# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Postponing Signing Configuration setup to the execution phase using providers
  """

[agpVersion]
min = "9.3"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "assembleDebug",
]
validationTasks = [
    "validateDebug"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Signing Configuration",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "APIs/SigningConfig.from()",
    "Signing Configuration"
]
