# optional (if present and non-blank) name to use in the index
indexName = "Transform Manifest (Meta-data)"
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = "transformManifest"

description ="""
  This recipe demonstrates how to use the Artifacts API to transform the Android Manifest.
  It injects a custom <meta-data> element containing a value from another task.
  """

[agpVersion]
min = "9.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkDebugMergedManifest"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Android Manifest",
    "Themes/Artifact API",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/variant.artifacts.get()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.artifacts.use().wiredWithFiles().toTransform()",
    "APIs/Component.artifacts",
    "APIs/Artifacts.use()",
    "APIs/Artifacts.get()",
    "APIs/TaskBasedOperation.wiredWithFiles()",
    "APIs/InAndOutFileOperationRequest.toTransform()",
    "Call chains/task.outputs.upToDateWhen {}",
    "APIs/TaskOutputs.upToDateWhen()",
    "APIs/task.getOutputs()",
    "APIs/SingleArtifact.MERGED_MANIFEST",
    "Custom Tasks/Manifest Transformation"
]