# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This recipe demonstrates how to build a library with Android Kotlin Multiplatform Library plugin
  """

[agpVersion]
min = "9.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":shared:assembleAndroidMain",
    ":shared:testAndroidHostTest",
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Plugin Features/Kotlin Multiplatform"
]
